[package]
name = "webkit2gtk-sys"
version = "0.3.1"
authors = ["The Gtk-rs Project Developers"]

categories = ["api-bindings", "gui"]
description = "Rust binding for webkit-gtk library"
repository = "https://github.com/gtk-rs/webkit2gtk-rs"
license = "MIT"
homepage = "http://gtk-rs.org"

keywords = ["webkit", "gtk-rs", "gnome", "GUI"]

build = "build.rs"
links = "web_kit2"

[badges]
travis-ci = { repository = "gtk-rs/webkit2gtk-rs" }

[lib]
name = "webkit2gtk_sys"

[features]
v2_6 = []
v2_8 = ["v2_6"]
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.9"
libc = "0.2"
atk-sys = "^0.3.3"
cairo-sys-rs = "^0.3.3"
gdk-sys = "^0.3.3"
gdk-pixbuf-sys = "^0.3.3"
gio-sys = "^0.3.3"
glib-sys = "^0.3.3"
gobject-sys = "^0.3.3"
gtk-sys = "^0.3.3"
pango-sys = "^0.3.3"
javascriptcore-rs-sys = "^0.1.0"
soup-sys = "^0.3.3"
